name: sample-workflow
on: [push]
jobs:
  explore-first-github-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: List files in repo
        run:
          ls ${{github.worspace}}
      - run: echo "Status is ${{job.status}}."
